// <auto-generated />
namespace DataMaintenance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2));
        
        string IMigrationMetadata.Id
        {
            get { return "202409230847215_m2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
